trigger:
  branches:
    include:
      - main

variables:
  imageRepository: 'pipelines-java'
  acrServiceConnection: 'sc-acr'
  acrName: 'acrpipelinesjava14858.azurecr.io'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Construir y publicar imagen'
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and push image to ACR'
      inputs:
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: 'Desplegar en AKS'
  dependsOn: Build
  jobs:
  - deployment: DeployToAKS
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'aks-devops-lab'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@1
            displayName: 'Deploy to AKS'
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'sc-azure-arm'
              azureResourceGroup: 'rg-devops-lab'
              kubernetesCluster: 'aks-devops-lab'
              namespace: 'default'
              manifests: |
                k8s/deployment.yaml
                k8s/service.yaml
              containers: '$(acrName)/$(imageRepository):$(tag)'
