apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelines-java-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipelines-java
  template:
    metadata:
      labels:
        app: pipelines-java
    spec:
      containers:
      - name: pipelines-java
        image: acrpipelinesjava14858.azurecr.io/pipelines-java:latest
        ports:
        - containerPort: 8080
